### ISSUE TITLE
Error raised using code from main: 4dc017d03d65dad31871e36b6d1fd59439d80b34

### ISSUE THREAD

**Issue by jwhonce** [Nriver/trilium-py#22]
```python
Traceback (most recent call last):
  File "/home/jhonce/Projects/trilium-addons/bugSLA/bugSLA.py", line 25, in <module>
    from trilium_py.client import ETAPI
  File "/home/jhonce/Projects/Python/trilium-py/src/trilium_py/client.py", line 18, in <module>
    from .utils.note_util import beautify_content, sort_note_by_headings
  File "/home/jhonce/Projects/Python/trilium-py/src/trilium_py/utils/note_util.py", line 7, in <module>
    from trilium_py.src.trilium_py.utils.html_util import sort_h_tags_with_hierarchy
ModuleNotFoundError: No module named 'trilium_py.src'
```

Using python 3.11 and trilium-py installed using `python -m pip install --user -e .`

**Comment by Nriver** [comment]
Thanks for the notice.
fixed in fecb1eefd6cb40fc0bc59f4f56df76cd78e35a0f
